### ISSUE TITLE
How would you handle Role Based Access Control?

### ISSUE THREAD

**Issue by jericopulvera** [creatrixity/adonis-hexa#5]

**Comment by creatrixity** [comment]
Hi, @jericopulvera were you able to get good answers to the issue as I was about to suggest one.

**Comment by jericopulvera** [comment]
Please do suggest. 😉

**Comment by creatrixity** [comment]
Hi, @jericopulvera. Role based access control is generally best abstracted to a separate service or package.

I can recommend the [Adonis ACL package](https://www.npmjs.com/package/adonis-acl) as a clean way to achieve your goal.

After installing the package

```
npm i adonis-acl --save
```

...and registering it

```js
const providers = [
  ...
  'adonis-acl/providers/AclProvider',
  ...
]
 
const aceProviders = [
  ...
  'adonis-acl/providers/CommandsProvider',
  ...
]
```
and carrying out other configuration procedures, you could use it like below if you are trying to ensure only administrator or moderators may access a route.

```js
// check roles
Route
  .get('/users')
  .middleware(['auth', 'is:(administrator || moderator) && !customer'])
```

**Comment by jericopulvera** [comment]
How about the directories separation?

Usually In a normal adonis app I do it like this

app/Controllers/Http/Admin/DashboardController.js
app/Controllers/Http/DashboardController.js

How would you suggest I do it in this framework?

**Comment by creatrixity** [comment]
Sorry, for the wait. Been really busy recently.

Unfortunately, for now adding a new sub directory means hacking the providers directly. I'm on a mobile, will give an example when I'm on the pc.
